/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bear.glb
*/

import React from "react"
import { useGLTF } from "@react-three/drei"

export function Bear(props: any) {
	const { nodes, materials } = useGLTF("/bear.glb") as any
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.Object_4.geometry}
				material={materials.Baerenbrunnen_O_Material_u1_v1}
			/>
		</group>
	)
}

useGLTF.preload("/bear.glb")
